config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :investments
  resources :groups

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'investments-ext', to: 'investments#index_external', as: 'external_investments'
  get 'investments-all', to: 'investments#index_all', as: 'all_investments'
end

app/models/investment.rb
class Investment < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :amount, presence: true
  validates :crypto, presence: true
  validates :group_id, presence: true

  validates :amount, numericality: { greater_than: 0, less_than: 1_000_000 }
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  before_action :set_investment, only: %i[show edit update destroy]
  before_action :authenticated, only: %i[edit update destroy home show new index]

  # GET /investments or /investments.json
  def index
    @investments = Investment.all
  end

  def index_external
    @investments = Investment.all
  end

  def index_all
    @investments = Investment.all
  end

  # GET /investments/1 or /investments/1.json
  def show; end

  # GET /investments/new
  def new
    @investment = Investment.new
  end

  # GET /investments/1/edit
  def edit; end

  # POST /investments or /investments.json
  def create
    @investment = Investment.new(investment_params)
    @investment.group_id = Group.all.where('name = ?', params['investment']['group_id']).select(:id).first.id

    @investment.user_id = current_user.id

    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: 'Investment was successfully created.' }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1 or /investments/1.json
  def update
    respond_to do |format|
      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: 'Investment was successfully updated.' }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1 or /investments/1.json
  def destroy
    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_url, notice: 'Investment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  helper_method :logged_in?

  def logged_in?
    !current_user.nil?
  end

  def authenticated
    return if logged_in?

    flash[:alert] = 'You need to login or sign up to access'
    redirect_to '/login'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_investment
    @investment = Investment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def investment_params
    params.require(:investment).permit(:crypto, :amount, :user_id)
  end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_with(model: @investment, class: "w-100") do |form| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
        <% @investment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :crypto, "Select crypto:", class: "form-label" %>
    <%= form.select :crypto, ['Bitcoin', 'Ethereum', 'XRP', 'Dogecoin', "USD (no crypto)"],
        {}, {class: "form-select form-select-lg mb-3"}  %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :group_id, "Select group:", class: "form-label" %>
    <%= form.select :group_id, Group.select(:name).map(&:name),
        {}, {class: "form-select form-select-lg mb-3"}  %>
  </div>
  <hr>
  <div class="field">
    <%= form.label :amount, "Amount:", class: "form-label" %>
    <%= form.number_field :amount, step: :any, class: "form-control" %>
  </div>

  <div class="link-container position-relative">
    <div class="btn2 btn-outline-green actions d-fixed position-fixed bottom-0 start-50 
          translate-middle-x w-100">
      <%= form.submit class: "btn2 btn-outline-green w-100 border border-white" %>
      </div>
  <div>
<% end %>

app/views/investments/create.html.erb
<h1>Investments#create</h1>
<p>Find me in app/views/investments/create.html.erb</p>

app/views/investments/destroy.html.erb
<h1>Investments#destroy</h1>
<p>Find me in app/views/investments/destroy.html.erb</p>

app/views/investments/edit.html.erb
<h1 class="my-5">Editing Investments</h1>

<div class="card-form-investment">
    <%= render 'form', user: @investment %>
</div>

app/views/investments/index.html.erb
<div class="d-flex flex-wrap justify-content-between text-muted p-3 bg-white">
    <strong class="my-auto">Total USD invested:</strong>
    <h3 class="fs-3 ms-2"><%= total_amount_internal(current_user)%> USD</h3>
</div>

<div class="link-container position-relative">
  <div class="btn2 btn-outline-green d-fixed position-fixed bottom-0 start-50 
        translate-middle-x w-100">
    <%= link_to 'New Investment', new_investment_path, 
        class: "btn2 btn-outline-green w-100 border border-white" %>
    </div>
<div>

<div class="d-flex flex-wrap">
<% @investments.where("user_id = ? AND group_id != 5", current_user.id).order("created_at DESC").each do |investment|  %>

<div class="mx-auto m-3 card-show bg-white p-3 gray_text_medium font-bold max-560">
  <div class="d-flex">
    <%= check_image_by_group_id(investment.group_id) %>
    <div class="fs-6 d-flex align-items-center mx-2">
      <strong>Group:
        <%= Group.where(id: investment.group_id).select("name").first["name"] %>
      </strong>
    </div>
  </div>
  <hr>
  <strong class="my-2 d-block fs-6">Money unit: <%= investment.crypto %></strong>
  <span class="gray_text_low font-light"> <%= investment.created_at.to_s(:long) %> </span>
  <hr>
  <div class="d-flex flex-wrap justify-content-between">
    <h6 class="my-auto">TOTAL AMOUNT:</h6>
    <strong class="fs-3 ms-2"><%= investment.amount %></strong>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <%= link_to 'Edit', edit_investment_path(investment), class: "text-muted font-light text-decoration-none mx-2" %> |
    <%= link_to 'Show', investment, class: "text-muted font-light text-decoration-none mx-2" %>
  </div>
</div>

<% end %>
</div>

app/views/investments/index_all.html.erb
<div class="d-flex flex-wrap justify-content-between text-muted p-3 bg-white">
    <strong class="my-auto">Total USD invested:</strong>
    <h3 class="fs-3 ms-2"><%= total_amount_all %> USD</h3>
</div>

<div class="link-container position-relative">
  <div class="btn2 btn-outline-green d-fixed position-fixed bottom-0 start-50 
        translate-middle-x w-100">
    <%= link_to 'New Investment', new_investment_path, 
        class: "btn2 btn-outline-green w-100 border border-white" %>
    </div>
<div>

<div class="content-investments">
<% @investments.order("created_at DESC").each do |investment|  %>

<div class="m-3 card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto">
  <div class="d-flex">
    <%= check_image_by_group_id(investment.group_id) %>
    <div class="fs-6 d-flex align-items-center mx-2">
      <strong>Investment</strong>
    </div>
  </div>
  <hr>
  <strong class="my-2 d-block fs-6">Money unit: <%= investment.crypto %></strong>
  <span class="gray_text_low font-light"> <%= investment.created_at.to_s(:long) %> </span>
  <hr>
  <div class="d-flex flex-wrap justify-content-between">
    <h6 class="my-auto">TOTAL AMOUNT:</h6>
    <strong class="fs-3 ms-2"><%= investment.amount %></strong>
  </div>
</div>

<% end %>
</div>

app/views/investments/index_external.html.erb
<div class="d-flex flex-wrap justify-content-between text-muted p-3 bg-white">
    <strong class="my-auto">Total USD invested:</strong>
    <h3 class="fs-3 ms-2"><%= total_amount_external(current_user)%> USD</h3>
</div>

<div class="link-container position-relative">
  <div class="btn2 btn-outline-green d-fixed position-fixed bottom-0 start-50 
        translate-middle-x w-100">
    <%= link_to 'New Investment', new_investment_path, 
        class: "btn2 btn-outline-green w-100 border border-white" %>
    </div>
<div>

<div class="d-flex flex-wrap">
<% @investments.where("user_id = ? AND group_id = 5", current_user.id).order("created_at DESC").each do |investment|  %>

<div class="m-3 card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto">
  <div class="d-flex">
    <%= check_image_by_group_id(investment.group_id) %>
    <div class="fs-6 d-flex align-items-center mx-2">
      <strong>External - No Group</strong>
    </div>
  </div>
  <hr>
  <strong class="my-2 d-block fs-6">Money unit: <%= investment.crypto %></strong>
  <span class="gray_text_low font-light"> <%= investment.created_at.to_s(:long) %> </span>
  <hr>
  <div class="d-flex flex-wrap justify-content-between">
    <h6 class="my-auto">TOTAL AMOUNT:</h6>
    <strong class="fs-3 ms-2"><%= investment.amount %></strong>
  </div>
  <div class="d-flex justify-content-center mt-3">
    <%= link_to 'Edit', edit_investment_path(investment), class: "text-muted font-light text-decoration-none mx-2" %> |
    <%= link_to 'Show', investment, class: "text-muted font-light text-decoration-none mx-2" %>
  </div>
</div>

<% end %>
</div>

app/views/investments/new.html.erb
<h1 class="my-5">New Investment</h1>

<div class="bg-white p-5 w-100 d-flex justify-content-center align-items-center
            fs-4 text-muted text_gray_low text-center">
    <% if Group.count != 0 %>
        <%= render 'form', investment: @investment %>
    <% else %>
        <p>You don't have groups!  Feel free to create a group first</p>
        <%= link_to 'New group',new_group_path %>
    <% end %>
</div>

app/views/investments/show.html.erb
<h1 class="my-5">Details</h1>
<div class="card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto">
  <div class="d-flex">
    <%= check_image_by_group_id(@investment.group_id) %>
    <div class="fs-6 d-flex align-items-center mx-2">
      <strong>Group:
        <%= Group.where(id: @investment.group_id).select("name").first["name"] %>
      </strong>
    </div>
  </div>
  <hr>
  <strong class="my-2 d-block fs-6">Money unit: <%= @investment.crypto %></strong>
  <span class="gray_text_low font-light"> <%= @investment.created_at.to_s(:long) %> </span>
  <hr>
  <div class="d-flex flex-wrap justify-content-between">
    <h6 class="my-auto">TOTAL AMOUNT:</h6>
    <strong class="fs-3 ms-2"><%= @investment.amount %></strong>
  </div>
  <% if current_user.id == @investment.user_id  %>
    <div class="link-container position-relative">
      <div class="btn2 btn-outline-green d-fixed position-fixed bottom-0 start-50 
            translate-middle-x w-100">
        <%= link_to 'Edit Investment', edit_investment_path(@investment), 
            class: "btn2 btn-outline-green w-100 border border-white" %>
        </div>
    <div>
  <% end %>
</div>

app/views/investments/update.html.erb
<h1>Investments#update</h1>
<p>Find me in app/views/investments/update.html.erb</p>