config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :investments
  resources :groups

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'investments-ext', to: 'investments#index_external', as: 'external_investments'
  get 'investments-all', to: 'investments#index_all', as: 'all_investments'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :name, length: { minimum: 4, maximum: 24 }

  belongs_to :user

  has_many :investments

  has_one_attached :icon
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticated, only: %i[edit update show destory new index]

  # GET /groups or /groups.json
  def index
    @groups = Group.all.includes(investments: [:user])
  end

  # GET /groups/1 or /groups/1.json
  def show
    @investments = Investment.includes(:user).where('user_id = ? AND group_id = ?', current_user.id, @group.id)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  helper_method :logged_in?

  def logged_in?
    !current_user.nil?
  end

  def authenticated
    return if logged_in?

    flash[:alert] = 'You need to login or sign up to access'
    redirect_to '/login'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :user_id, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def check_image_by_group_id(group_id)
    if Group.all.where(id: group_id).first.icon.persisted?
      link_to image_tag(Group.where(id: group_id).first.icon,
                        style: 'height:64px;width:64px;'), groups_path
    else
      link_to image_tag('http://a4.mzstatic.com/us/r1000/046/Purple/bd/8f/fd/mzl.emkswtfe.jpg',
                        style: 'height:64px;width:64px;'),
              groups_path
    end
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, class: "w-100") do |form| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> Prohibited this group from being saved:</h2>
      <ul>
        <% @group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class: "value-input", 
    class: "form-control fs-4 text-muted text-center", placeholder: "Type the name" %>
  </div>

  <div class="field">
    <%= form.label :icon, "Upload a photo to represent your group", class: "form-label d-block text-center text-muted fs-4 mt-5" %>
    <%= form.file_field :icon, class: "form-control text-muted mb-3"  %>
  </div>


  <div class="link-container position-relative">
    <div class="btn2 btn-outline-green actions d-fixed position-fixed bottom-0 start-50 
          translate-middle-x w-100">
      <%= form.submit class: "btn2 btn-outline-green w-100 border border-white" %>
      </div>
  <div>
<% end %>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/edit.html.erb
<h1 class="my-5">Editing Group</h1>

<div class="bg-white p-5">
    <%= render 'form', user: @group %>
</div>

app/views/groups/index.html.erb
<h1>Groups</h1>

<div class="link-container position-relative">
  <div class="btn2 btn-outline-green d-fixed position-fixed bottom-0 start-50 
        translate-middle-x w-100">
    <%= link_to 'New Group', new_group_path, 
        class: "btn2 btn-outline-green w-100 border border-white" %>
    </div>
<div>

<div class="groups-container">

<% @groups.all.where("id != 5").order("created_at DESC").each do |group|  %>

  <div class="m-3 card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto">
    <div class="d-flex">
      <%= check_image_by_group_id(group.id) %>
      <div class="fs-6 d-flex align-items-center mx-2">
        <strong><%= group.name %></h3></strong>
      </div>
    </div>
    <hr>
    <span class="gray_text_low font-light"> <%= group.created_at.to_s(:long) %> </span>
    <hr>

    <div class="d-flex justify-content-center mt-3">
      <%= link_to 'Edit', edit_group_path(group), class: "text-muted font-light text-decoration-none mx-2" %> |
      <%= link_to 'Show', group, class: "text-muted font-light text-decoration-none mx-2" %>
    </div>
  </div>
  
<% end %>

</div>

app/views/groups/new.html.erb
<h1 class="my-4">Creating Group</h1>

<div class="bg-white p-5">

<%= render 'form', group: @group %>

</div>

app/views/groups/show.html.erb
<div class="m-3 card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto text-center">
    <div class="d-flex justify-content-center">
      <%= check_image_by_group_id(@group.id) %>
      <div class="fs-6 d-flex align-items-center mx-2">
        <strong><%= @group.name %></h3></strong>
      </div>
    </div>
    <hr>
    <span class="gray_text_low font-light"> <%= @group.created_at.to_s(:long) %> </span>
    <hr>

    <div class="d-flex justify-content-center mt-3">
      <%= link_to 'Edit', edit_group_path(@group), class: "text-muted font-light text-decoration-none mx-2" %> |
      <%= link_to 'Show', @group, class: "text-muted font-light text-decoration-none mx-2" %>
    </div>
  </div>

<h4 class="my-5 text-muted text-center">Group investments:</h4>

<div class="groups-container">

<% @investments.each do |investment|  %>

<div class="m-3 card-show bg-white p-3 gray_text_medium font-bold max-560 mx-auto">
  <div class="d-flex">
    <%= check_image_by_group_id(investment.group_id) %>
    <div class="fs-6 d-flex align-items-center mx-2">
      <strong>Group:
        <%= Group.where(id: investment.group_id).select("name").first["name"] %>
      </strong>
    </div>
  </div>
  <hr>
  <strong class="my-2 d-block fs-6">Money unit: <%= investment.crypto %></strong>
  <span class="gray_text_low font-light"> <%=investment.created_at.to_s(:long) %> </span>
  <hr>
  <div class="d-flex flex-wrap justify-content-between">
    <h6 class="my-auto">TOTAL AMOUNT:</h6>
    <strong class="fs-3 ms-2"><%= investment.amount %></strong>
  </div>
  <% if current_user.id == investment.user_id  %>
    <div class="d-flex justify-content-center mt-3">
      <%= link_to 'Edit', edit_investment_path(investment), class: "text-muted font-light text-decoration-none mx-2" %> |
      <%= link_to 'Show', investment, class: "text-muted font-light text-decoration-none mx-2" %>
    </div>
  <% end %>
</div>

<% end %>

</div>

app/views/groups/update.html.erb
<h1>Groups#update</h1>
<p>Find me in app/views/groups/update.html.erb</p>