config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :investments
  resources :groups

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'investments-ext', to: 'investments#index_external', as: 'external_investments'
  get 'investments-all', to: 'investments#index_all', as: 'all_investments'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticated, only: %i[index]

  def index
    Group.create(id: 5, name: 'No group', user_id: 1) if Group.all.where(id: 5).first.nil?
  end

  private

  helper_method :logged_in?

  def logged_in?
    !current_user.nil?
  end

  def authenticated
    return if logged_in?

    flash[:alert] = 'You need to login or sign up to access'
    redirect_to '/login'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1 class="my-5">User Profile</h1>

<div>
  <ul class="links-card max-560 mt-3 mx-auto">
      <% if current_user.avatar.persisted? %>
        <%= link_to image_tag(current_user.avatar, style: "height:164px;width:164px;"), root_path %>
      <% else %>
        <%= link_to image_tag("http://a4.mzstatic.com/us/r1000/046/Purple/bd/8f/fd/mzl.emkswtfe.jpg",
        style: "height:164px;width:164px;"), root_path %>
      <% end %>
      <div class="mb-5 text-light text-center">
        <h2 class="fs-5 my-3">Hi <%= current_user.name %>!</h2>
        <%= link_to "Edit profile", edit_user_path(current_user), class: "d-block text-decoration-none" %>
      </div>
      <li class="nav-item">
        <%= link_to 'All my portfolio', investments_path, class: "nav-link link-home" %>
      </li>
      <li class="nav-item">
        <%= link_to 'All my external investments', external_investments_path, class: "nav-link link-home" %>
      </li>
      <li class="nav-item">
        <%= link_to 'All portfolios', groups_path, class: "nav-link link-home" %>
      </li>
      <li class="nav-item">
        <%= link_to 'All investments', all_investments_path, class: "nav-link link-home" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log out', logout_path, class: "nav-link link-home" %>
      </li>
    </ul>
</div>