config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :investments
  resources :groups

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'investments-ext', to: 'investments#index_external', as: 'external_investments'
  get 'investments-all', to: 'investments#index_all', as: 'all_investments'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid text-light">
    <%= link_to "Crypto Portfolios", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"> <%= image_tag("hamburger.png") %></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <% if current_user != nil %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'All my portfolio', investments_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'All my external investments', external_investments_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'All portfolios', groups_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'All investments', all_investments_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log out', logout_path, class: "nav-link" %>
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupOurTransactions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

  <body class="proxima_light_font body">
    <div class="container-xxl">
      <%= render "layouts/navbar" %>
    </div>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container-xxl">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </body>
</html>